### PR TITLE
Innovatech

### PR DESCRIPTION
**Pull request by pabmf**
Added RpLidar A3 integration, Innovatech's office map, customizations, and installation instructions.

### CODE REVIEW

**Comment by timrae** [comment]
In the future, better make a more descriptive title for the PR lol

**Comment by timrae** [comment]
@vale-innova 
One thing that just occurred to me that might cause problems in the future is that committing changes to the README might cause unnecessary merge conflicts in the future.

**Comment by vale-innova** [comment]
@timrae, yes I think it is better to have a separate README. Could you please advice on the details? is it README.not-md, /not-main-path/README.md, REAMDE-INNOVA.md ...

**Comment by timrae** [comment]
`REAMDE-INNOVA.md` sounds good to me

**Pull request merged**
